from django.urls import path
from .views import (
    SignupView, LoginView, ForgotPasswordView, ResetPasswordView, VerifyOTPView,
    KYCMeAPIView, KYCSubmitAPIView,
    OTPVerificationView, ResendOTPView, VerifyEmailView, ResendEmailVerificationView,
    landing_page, role_selection, register_page, login_page, home_page, dashboard,
    terms_of_service_page, privacy_policy_page,
    farmer_dashboard, vendor_dashboard, expert_dashboard, user_dashboard,     admin_dashboard,
    admin_kyc_management, admin_kyc_view_json, admin_user_management, admin_user_view_json, admin_content_management,
    admin_marketplace_oversight, admin_collections_payouts,
    admin_appointment_management, admin_chat_reports, admin_chat_thread_view,
    kyc_page, profile_page, settings_page, change_password, order_detail_page,
    appointment_request_page,
    chat_threads_page, chat_thread_detail, chat_start,
    api_chat_messages, api_chat_send, api_chat_start,
    api_tools_add, api_crops_add,
    api_tools_list, api_crops_list, api_orders_create, api_appointments_book,
    api_payments_esewa_initiate, api_orders_mark_payment,
    favicon_view, forgot_password_page, reset_password_page, otp_verification_page, verify_email_page,
    logout_view, google_signup_start_view,
    esewa_initiate, esewa_success, esewa_failure,
    support_hub, admin_support_desk, support_ticket_detail,
    api_support_config, api_support_faqs, api_support_my_tickets, api_support_create_ticket,
    api_support_ticket_detail, api_support_reply, api_support_open_tickets,
    api_support_assign, api_support_status,
    api_notifications_list, api_notification_mark_read, api_notification_mark_all_read,
)
urlpatterns = [
    # Frontend pages
    path('', landing_page, name='landing'),
    path('favicon.ico', favicon_view),
    path('home/', home_page, name='home'),
    path('terms-of-service/', terms_of_service_page, name='terms_of_service'),
    path('privacy-policy/', privacy_policy_page, name='privacy_policy'),
    path('role-selection/', role_selection, name='role-selection'),
    path('register/', register_page, name='register'),
    path('register/google-signup/', google_signup_start_view, name='google_signup_start'),
    path('login/', login_page, name='login'),
    path('forgot-password/', forgot_password_page, name='forgot_password'),
    path('otp-verification/', otp_verification_page, name='otp_verification'),
    path('verify-email/', verify_email_page, name='verify_email'),
    path('reset-password/', reset_password_page, name='reset_password'),
    path('dashboard/', dashboard, name='dashboard'),
    path('profile/', profile_page, name='profile'),
    path('settings/', settings_page, name='settings'),
    path('settings/change-password/', change_password, name='change_password'),
    path('kyc/', kyc_page, name='kyc'),
    path('orders/<int:order_id>/', order_detail_page, name='order_detail'),
    path('farmer-dashboard/', farmer_dashboard, name='farmer_dashboard'),
    path('vendor-dashboard/', vendor_dashboard, name='vendor_dashboard'),
    path('expert-dashboard/', expert_dashboard, name='expert_dashboard'),
    path('user-dashboard/', user_dashboard, name='user_dashboard'),
    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/kyc/', admin_kyc_management, name='admin_kyc_management'),
    path('admin-dashboard/kyc/view/<int:kyc_id>/', admin_kyc_view_json, name='admin_kyc_view_json'),
    path('admin-dashboard/users/', admin_user_management, name='admin_user_management'),
    path('admin-dashboard/users/view/<int:user_id>/', admin_user_view_json, name='admin_user_view_json'),
    path('admin-dashboard/content/', admin_content_management, name='admin_content_management'),
    path('admin-dashboard/marketplace/', admin_marketplace_oversight, name='admin_marketplace_oversight'),
    path('admin-dashboard/collections-payouts/', admin_collections_payouts, name='admin_collections_payouts'),
    path('admin-dashboard/appointments/', admin_appointment_management, name='admin_appointment_management'),
    path('admin-dashboard/chats-reports/', admin_chat_reports, name='admin_chat_reports'),
    path('admin-dashboard/chats-reports/<int:thread_id>/', admin_chat_thread_view, name='admin_chat_thread_view'),
    path('appointments/request/', appointment_request_page, name='appointment_request'),
    path('chat/', chat_threads_page, name='chat_threads'),
    path('chat/start/<int:expert_id>/', chat_start, name='chat_start'),
    path('chat/<int:thread_id>/', chat_thread_detail, name='chat_thread'),
    path('api/chat/thread/<int:thread_id>/messages/', api_chat_messages, name='api_chat_messages'),
    path('api/chat/thread/<int:thread_id>/send/', api_chat_send, name='api_chat_send'),
    path('api/chat/start/<int:expert_id>/', api_chat_start, name='api_chat_start'),
    path('api/tools/add/', api_tools_add, name='api_tools_add'),
    path('api/crops/add/', api_crops_add, name='api_crops_add'),
    path('api/tools/', api_tools_list, name='api_tools_list'),
    path('api/crops/', api_crops_list, name='api_crops_list'),
    path('api/orders/create/', api_orders_create, name='api_orders_create'),
    path('api/orders/payment/', api_orders_mark_payment, name='api_orders_mark_payment'),
    path('api/payments/esewa/initiate/', api_payments_esewa_initiate, name='api_payments_esewa_initiate'),
    path('api/appointments/book/', api_appointments_book, name='api_appointments_book'),
    path('support/', support_hub, name='support_hub'),
    path('admin-dashboard/support/', admin_support_desk, name='admin_support_desk'),
    path('support/ticket/<int:ticket_id>/', support_ticket_detail, name='support_ticket'),
    path('payment/esewa/initiate/', esewa_initiate, name='esewa_initiate'),
    path('payment/esewa/success/', esewa_success, name='esewa_success'),
    path('payment/esewa/failure/', esewa_failure, name='esewa_failure'),
    path('api/support/config/', api_support_config, name='api_support_config'),
    path('api/support/faqs/', api_support_faqs, name='api_support_faqs'),
    path('api/support/my-tickets/', api_support_my_tickets, name='api_support_my_tickets'),
    path('api/support/tickets/', api_support_create_ticket, name='api_support_create_ticket'),
    path('api/support/tickets/<int:ticket_id>/', api_support_ticket_detail, name='api_support_ticket_detail'),
    path('api/support/tickets/<int:ticket_id>/reply/', api_support_reply, name='api_support_reply'),
    path('api/support/open-tickets/', api_support_open_tickets, name='api_support_open_tickets'),
    path('api/support/tickets/<int:ticket_id>/assign/', api_support_assign, name='api_support_assign'),
    path('api/support/tickets/<int:ticket_id>/status/', api_support_status, name='api_support_status'),
    path('api/notifications/', api_notifications_list, name='api_notifications_list'),
    path('api/notifications/<int:notification_id>/read/', api_notification_mark_read, name='api_notification_mark_read'),
    path('api/notifications/mark-all-read/', api_notification_mark_all_read, name='api_notification_mark_all_read'),
    path('logout/', logout_view, name='logout'),
]

api_urlpatterns = [
    path('signup/', SignupView.as_view(), name='api-signup'),
    path('login/', LoginView.as_view(), name='api-login'),
    path('verify-email/', VerifyEmailView.as_view(), name='api-verify-email'),
    path('resend-email-verification/', ResendEmailVerificationView.as_view(), name='api-resend-email-verification'),
    path('verify-otp/', OTPVerificationView.as_view(), name='api-verify-otp'),
    path('verify-reset-otp/', VerifyOTPView.as_view(), name='api-verify-reset-otp'),
    path('resend-otp/', ResendOTPView.as_view(), name='api-resend-otp'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='api-forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='api-reset-password'),
]

kyc_api_urlpatterns = [
    path('me/', KYCMeAPIView.as_view(), name='api-kyc-me'),
    path('submit/', KYCSubmitAPIView.as_view(), name='api-kyc-submit'),
]
