# Generated by Django 5.2 on 2025-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('farmer', 'Farmer'), ('agricultural_expert', 'Agricultural Expert'), ('vendor', 'Vendor'), ('admin', 'Admin')], default='buyer', max_length=20),
        ),
    ]
