# Generated by Django 5.2 on 2025-12-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('farmer', 'Farmer'), ('agricultural_expert', 'Agricultural Expert'), ('vendor', 'Vendor')], default='buyer', max_length=20),
        ),
    ]
