# Generated by Django 5.2.8 on 2026-01-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_expertprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
