# Generated by Django 5.2 on 2026-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_cropsale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertchatthread',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='expertchatthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
