# Generated by Django 5.2 on 2026-01-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrequest',
            name='certificate_document',
            field=models.FileField(blank=True, help_text='Required for agricultural experts - Professional certificate or qualification', null=True, upload_to='kyc_certificate_documents/'),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='company_document',
            field=models.FileField(blank=True, help_text='Required for vendors - Company registration or business license', null=True, upload_to='kyc_company_documents/'),
        ),
    ]
