# Generated by Django 5.2 on 2026-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_kycrequest_certificate_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tool_images/'),
        ),
    ]
