# Generated by Django 5.2 on 2026-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vendortool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingtip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expert_content_images/'),
        ),
    ]
