# Generated by Django 5.2 on 2026-02-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.expertprofile')),
            ],
            options={
                'verbose_name_plural': 'Expert availabilities',
                'ordering': ('date',),
                'unique_together': {('expert', 'date')},
            },
        ),
    ]
