# Generated by Django 5.2 on 2026-02-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_expert_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertappointment',
            name='visit_status',
            field=models.CharField(blank=True, choices=[('visited', 'Visited'), ('will_visit', 'Will visit'), ('waiting', 'They have to wait')], help_text='For accepted appointments: Visited / Will visit / They have to wait.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expertappointment',
            name='response_message',
            field=models.TextField(blank=True, help_text='Doctor message: reason for reject or note for accept.', null=True),
        ),
    ]
