# Generated by Django 5.2 on 2026-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_type',
            field=models.CharField(blank=True, help_text='e.g., Equipment supplier, Seeds & fertilizers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Business description', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
