# Generated by Django 5.2 on 2026-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_default_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Phone number (required for delivery)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_email',
            field=models.EmailField(blank=True, help_text='Email for this order (optional)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Delivery location/address', null=True),
        ),
    ]
