# Generated by Django 5.2 on 2026-02-24

from django.db import migrations, models


def set_existing_tips_approved(apps, schema_editor):
    FarmingTip = apps.get_model('accounts', 'FarmingTip')
    FarmingTip.objects.all().update(approval_status='approved', is_published=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingtip',
            name='approval_status',
            field=models.CharField(
                choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                default='pending',
                help_text='Content is visible to users only when Approved by admin.',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='farmingtip',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Set to True when admin approves.'),
        ),
        migrations.RunPython(set_existing_tips_approved, noop),
    ]
