# Generated by Django 5.2 on 2026-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_farmingtip_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payout_at',
            field=models.DateTimeField(blank=True, help_text='When admin paid this order’s amount to farmer/vendor', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(blank=True, choices=[('pending_payout', 'Pending payout'), ('paid', 'Paid to seller')], default='pending_payout', max_length=20, null=True),
        ),
    ]
