# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_order_payout_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expertavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='expertavailability',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Optional: slot start. Empty means whole day.', null=True),
        ),
        migrations.AddField(
            model_name='expertavailability',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Optional: slot end. Empty means whole day.', null=True),
        ),
        migrations.AlterModelOptions(
            name='expertavailability',
            options={'ordering': ('date', 'start_time'), 'verbose_name_plural': 'Expert availabilities'},
        ),
    ]
