# Generated by Django 5.2 on 2026-03-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_expert_availability_times'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='accounts_ot_user_id_b1f4b7_idx',
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('email_verify', 'Email verification')], default='login', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'is_used', 'is_verified'], name='accounts_ot_user_id_6a4b6f_idx'),
        ),
    ]
