# Generated by ChatGPT on 2026-03-06

from django.db import migrations


def forwards(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Backfill: any previously-active account is treated as email-verified.
    # This avoids locking out existing users when introducing email verification.
    User.objects.filter(is_active=True, email_verified=False).update(email_verified=True)


def backwards(apps, schema_editor):
    # No safe automatic rollback: leave values as-is.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0025_remove_otp_accounts_ot_user_id_b1f4b7_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

