# Generated by Django 5.2 on 2026-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_backfill_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, help_text='Small label above title, e.g. Explore, Suppliers', max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('link_target', models.CharField(default='#', help_text='Anchor or URL, e.g. #marketplace, #vendors', max_length=255)),
                ('cta_text', models.CharField(blank=True, help_text='Call-to-action, e.g. View marketplace →', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing_features/')),
                ('image_url', models.URLField(blank=True, help_text='Or use an external image URL (used if no image file)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Landing feature card',
                'verbose_name_plural': 'Landing feature cards',
                'ordering': ('display_order', 'created_at'),
            },
        ),
    ]
