# Generated by Django 5.2 on 2026-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_order_shipping_cost_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fee per appointment (Rs.). 0 = free. Can be set for future paid appointments.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
