# Generated by Django 5.2 on 2026-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_backfill_order_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='previous_released_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Earnings already released by admin before system tracking (e.g. 300)', max_digits=12),
        ),
    ]
