# Generated by Django 5.2 on 2026-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_add_chat_message_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertchatmessage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='chat_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='expertchatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
