# Generated by Django 5.2 on 2026-04-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_expert_appointment_cancelled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertappointment',
            name='visit_status',
            field=models.CharField(blank=True, choices=[('visited', 'Visited'), ('will_visit', 'Will visit'), ('waiting', 'Pending')], help_text='For accepted appointments: Will visit / Pending / Visited.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('ready_to_ship', 'Ready to ship'), ('shipped', 'Shipped'), ('on_the_way', 'On the way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
